"""Bundle wall/ into a single install.lua that a turtle can fetch and run.

    py -3 tools/make_installer.py

Getting eleven files onto eight turtles by hand is not realistic, and a normal
player has no access to the world save. So everything is packed into one file
that writes the rest out. Upload that one file to pastebin (or a gist), then on
each turtle:

    pastebin get <code> install
    install

Sources are embedded as Lua long strings. The bracket level is chosen so its
closing delimiter appears nowhere in any file, which matters because the source
is full of --[[ ]] comments that a naive [[ ]] would terminate early.
"""

import datetime
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "wall"
OUT = ROOT / "install.lua"

# config.lua is the one file the player edits, so it must never be clobbered by
# a reinstall. The installer writes it only when it is missing.
PRESERVE = {"wall/config.lua"}


def pick_level(texts):
    """Lowest long-bracket level whose closer occurs in none of the sources."""
    for n in range(1, 16):
        closer = "]" + "=" * n + "]"
        if all(
            (t + closer).index(closer) == len(t)
            for t in texts
        ):
            return n
    raise SystemExit("no safe long-bracket level found")


def main():
    files = sorted(SRC.glob("*.lua"))
    if not files:
        raise SystemExit(f"no .lua files in {SRC}")

    contents = {}
    for f in files:
        contents["wall/" + f.name] = f.read_text(encoding="utf-8")

    # A build id taken from the sources themselves, so it changes exactly when
    # the code does. raw.githubusercontent.com caches for several minutes, and
    # without this there is no way to tell a fresh install from a stale one.
    # Computed before version.lua is added, so it does not depend on itself.
    digest = hashlib.sha256()
    for path in sorted(contents):
        digest.update(path.encode("utf-8"))
        digest.update(contents[path].encode("utf-8"))
    build_id = digest.hexdigest()[:8]
    made = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    contents["wall/version.lua"] = (
        "-- Generated by tools/make_installer.py. Not part of the source tree;\n"
        "-- it exists so an installed turtle can say which build it is running.\n"
        f'return {{ build = "{build_id}", made = "{made}" }}\n'
    )

    n = pick_level(list(contents.values()))
    open_b, close_b = "[" + "=" * n + "[", "]" + "=" * n + "]"

    out = []
    out.append("--[[")
    out.append("  install -- unpacks the wall program onto this turtle.")
    out.append("")
    out.append("  Generated by tools/make_installer.py; do not edit by hand.")
    out.append("  Re-running is safe: it refreshes the program but leaves your")
    out.append("  edited wall/config.lua alone.")
    out.append("]]")
    out.append("")
    # The config schema version, read out of the bundled config so the
    # installer can tell an out-of-date one on the turtle.
    import re as _re
    m = _re.search(r"config\.version\s*=\s*(\d+)", contents["wall/config.lua"])
    out.append(f"local configVersion = {m.group(1) if m else 0}")
    out.append("")
    out.append("local preserve = {")
    for p in sorted(PRESERVE):
        out.append(f'  ["{p}"] = true,')
    out.append("}")
    out.append("")
    out.append("local files = {}")
    out.append("local order = {}")
    out.append("")

    for path in sorted(contents):
        out.append(f'order[#order + 1] = "{path}"')
        # A long string swallows one leading newline, so add one to give back.
        out.append(f'files["{path}"] = {open_b}')
        out.append(contents[path].rstrip("\n"))
        out.append(close_b)
        out.append("")

    out.append(
        r"""
if not fs.exists("wall") then fs.makeDir("wall") end

--- Is the config already on this turtle old enough to be missing settings the
--- program now needs?
local function staleConfig()
  if not fs.exists("wall/config.lua") then return false end
  local ok, existing = pcall(dofile, "wall/config.lua")
  if not ok or type(existing) ~= "table" then return true end
  return (existing.version or 0) < configVersion
end

local stale = staleConfig()

local written, kept = 0, 0

for _, path in ipairs(order) do
  if preserve[path] and fs.exists(path) then
    kept = kept + 1
    print("kept   " .. path)
  else
    local f = fs.open(path, "w")
    if not f then
      printError("could not write " .. path)
      return
    end
    f.write(files[path])
    f.close()
    written = written + 1
    print("wrote  " .. path)
  end
end

print("")
print(written .. " files written, " .. kept .. " kept.")

if stale then
  print("")
  printError("Your wall/config.lua is older than this build and is missing")
  printError("settings the program needs. It was kept so your edits survive.")
  printError("")
  printError("  rm wall/config.lua   then install again")
end
""".strip()
    )
    out.append(f'print("build {build_id}  ({made})")')
    out.append('print("")')
    out.append('print("Next:  wall/wall check")')
    out.append("")

    text = "\n".join(out)

    # newline="" so Windows does not rewrite every \n as \r\n. The turtles read
    # this file verbatim, and the embedded sources would carry those CRs into
    # every file it unpacks.
    with OUT.open("w", encoding="utf-8", newline="") as fh:
        fh.write(text)

    size = len(text.encode("utf-8"))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  build {build_id}  ({made})")
    print(f"  {len(contents)} files, bracket level {n}, {size:,} bytes")
    if size > 500_000:
        print("  WARNING: over pastebin's 512 KB limit", file=sys.stderr)


if __name__ == "__main__":
    main()
